# CircleCI 2.0 configuration file for Babyl

version: 2
jobs:
  build:
    docker:
       - image: circleci/ruby:2.3
         environment:
           RAILS_ENV: test

    working_directory: ~/circleci-test

    steps:
      - checkout

      - run:
          name: Bundler
          command: |
            bundle install

      - run:
          name: Set up test DB
          command: |
            bundle exec rake db:schema:load

      - run:
          name: run tests
          command: |
            bundle exec rspec spec/

  deploy-staging:
    docker:
       - image: circleci/ruby:2.3

    working_directory: ~/circleci-test

    steps:
      - checkout

      - run:
          name: Run setup script
          command: bash .circleci/setup-heroku.sh

      - add_ssh_keys:
          fingerprints:
            - "8b:48:5e:67:0e:c9:16:47:32:f2:87:0c:1f:c8:60:ad"

      - run:
          name: Deploy master to Heroku
          command: |
            git push git@heroku.com:$HEROKU_APP_NAME.git HEAD:refs/heads/master

      - run:
          name: DB Migrate
          command: |
            heroku run rake db:migrate --app $HEROKU_APP_NAME

      - run:
          name: Restart Dynos
          command: |
            heroku restart --app $HEROKU_APP_NAME

workflows:
  version: 2
  build-and-deploy:
    jobs:
      # - build
      - deploy-staging:
          # requires:
          #   - build
          filters:
             branches:
               only: master
      # - hold:
      #    type: approval
      #    requires:
      #      - build
